# Setup
title:               Covid in Wisconsin
tagline:             ''
description:         'Amateur analysis of our local Covid data.'
logo:                '/public/LogoCovidWI.png'
url:                 https://covid-wisconsin.com
baseurl:             ''
paginate:            5
permalink:           pretty
markdown:            kramdown

# About/contact
author:
  name:              Matt Bayer
  twitter:           MattBayerWI
  email:             

# Gems
plugins:
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-seo-tag
  
# Google Analytics
google_analytics: G-G84CM55HBV

# Options
relative_links:
  enabled:     true
  collections: true 
# Custom vars
version:          2.1.0
