name: Update Data from Wisconsin DHS

on: [workflow_dispatch]

jobs:
  update-data:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        conda install pandas
    - name: Run update functions
      run: |
        python UpdateDataAuto.py
    - name: Setup git config
      run: |
        # setup the username and email. 
        git config user.name "mattbayer"
        git config user.email "<>"
    - name: Commit updates
      run: |
        # Stage the file, commit and push
        git add .\\data\\Covid-Data-WI-State.csv
        git add .\\data\\Covid-Data-WI-County.csv
        git commit -m "Data update (auto)"
        git push origin master

